name: ci

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      scala_version:
        description: 'Scala version to publish'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SCALA_VERSION: ${{ inputs.scala_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: ./mill __.publishArtifacts + __.test

  publish-sonatype:
    if: github.repository == 'com-lihaoyi/acyclic' && contains(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    env:
      MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MILL_PGP_SECRET_BASE64: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY }}
      MILL_PGP_PASSPHRASE: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Maven Central
        run: ./mill -i mill.scalalib.SonatypeCentralPublishModule/